#!/bin/bash

# Build the binary
make clean
make

# Start the server
 echo "server { listen 8080; }" >> test_config
./webserver test_config

# Send a request to the server using curl
# TODO

# Verify the response from the server works as expected
# TODO

# Indicate success or failure with an appropriate exit code
# TODO

# Shutdown the webserver
# kill %1
# rm test_config